name: Ensure Android cmdline-tools and accept licenses
  shell: bash
  run: |
    set -e
    ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}"
    mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
    if [ ! -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
      TMP_DIR="$(mktemp -d)"
      curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o "$TMP_DIR/cli.zip"
      mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
      unzip -q "$TMP_DIR/cli.zip" -d "$TMP_DIR"
      # 拍扁目录，确保 latest/bin/sdkmanager 存在
      rm -rf "$ANDROID_SDK_ROOT/cmdline-tools/latest/*"
      mv "$TMP_DIR/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
    fi
    # yes 的 Broken pipe 不再致命
    yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses >/dev/null 2>&1 || true
    # 可选：确认一下
    "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --version || true

2) 安装 platforms/build-tools（统一用同一个 sdkmanager，所有命令都容错）
- 关键点：变量 SDKMGR 指向刚才的 binary，所有安装命令后面都接 || true。

- name: Install Android SDK (34/35)
  shell: bash
  run: |
    set -e
    SDKMGR="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
    yes | "$SDKMGR" --install "platform-tools" >/dev/null 2>&1 || true
    yes | "$SDKMGR" --install "platforms;android-35" "build-tools;35.0.0" >/dev/null 2>&1 || true
    yes | "$SDKMGR" --install "platforms;android-34" "build-tools;34.0.0" >/dev/null 2>&1 || true
    "$SDKMGR" --list | head -n 20 || true
