name: v8a APK

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  android-arm64:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17 (Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'
          cache: gradle
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties

      - name: Setup Flutter (from pubspec.yaml)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      # settings.gradle.kts 需要这个，否则会报 "flutter.sdk not set in local.properties"
      - name: Write android/local.properties (flutter.sdk)
        run: echo "flutter.sdk=${FLUTTER_ROOT}" > android/local.properties

      - name: Flutter pub get
        run: flutter pub get

      # 优先用 Secrets 的正式签名；没有就生成临时 release keystore（同样不会有 debug 水印）
      - name: Prepare release keystore
        env:
          SIGN_KEYSTORE_BASE64: ${{ secrets.SIGN_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          set -e
          mkdir -p android/app
          if [ -n "$SIGN_KEYSTORE_BASE64" ] && [ -n "$KEYSTORE_PASSWORD" ] && [ -n "$KEY_ALIAS" ] && [ -n "$KEY_PASSWORD" ]; then
            echo "$SIGN_KEYSTORE_BASE64" | base64 -d > android/app/key.jks
            {
              echo "storeFile=key.jks"
              echo "storePassword=$KEYSTORE_PASSWORD"
              echo "keyAlias=$KEY_ALIAS"
              echo "keyPassword=$KEY_PASSWORD"
            } > android/key.properties
          else
            if [ ! -f android/app/key.jks ]; then
              keytool -genkey -v -keystore android/app/key.jks \
                -keyalg RSA -keysize 2048 -validity 10000 \
                -storepass temp123456 -keypass temp123456 \
                -alias tempkey \
                -dname "CN=PiliPlus, OU=CI, O=PiliPlus, L=CN, S=CN, C=CN"
            fi
            {
              echo "storeFile=key.jks"
              echo "storePassword=temp123456"
              echo "keyAlias=tempkey"
              echo "keyPassword=temp123456"
            } > android/key.properties
          fi

      - name: Build APK (arm64-v8a only)
        shell: bash
        run: |
          set -e
          DEFINE_ARG=""
          if [ -f pili_release.json ]; then
            DEFINE_ARG="--dart-define-from-file=pili_release.json"
          fi
          # split-per-abi 只会产出 arm64、v7a、x86_64 三个，我们只取 arm64-v8a
          flutter build apk --release --split-per-abi $DEFINE_ARG

      - name: Read version
        id: version
        run: |
          VERSION=$(grep "^version:" pubspec.yaml | sed 's/version:[[:space:]]*//' | sed 's/+.*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Rename arm64 artifact
        shell: bash
        run: |
          set -e
          ARM64_APK="build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          test -f "$ARM64_APK"
          mkdir -p output
          cp "$ARM64_APK" "output/PiliPlus_android_${{ steps.version.outputs.version }}_arm64-v8a.apk"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android_arm64-v8a
          path: output/PiliPlus_android_*_arm64-v8a.apk
          if-no-files-found: error